require("dotenv").config()
const sequelize = require('./lib/sequelize')
const { User, UserClientFields } = require('./models/user')
// const { Course, CourseClientFields } = require('./models/course')
const { Assignment, AssignmentClientFields } = require('./models/assignment')
// const { Enrollment, EnrollmentClientFields } = require('./models/enrollment')
const { Submission, SubmissionClientFields } = require('./models/submission')

const userData = require('./data/users.json')
const courseData = require('./data/courses.json')
const assignmentData = require('./data/assignments.json')
const enrollmentData = require('./data/enrollments.json')
// const submissionData = require('./data/submissions.json')

sequelize.sync().then(async function () {
    await User.bulkCreate(userData, { fields: UserClientFields })
    // await Course.bulkCreate(courseData, { fields: CourseClientFields })
    await Assignment.bulkCreate(assignmentData, { fields: AssignmentClientFields })
    // await Enrollment.bulkCreate(enrollmentData, { fields: EnrollmentClientFields })
    // await Submission.bulkCreate(submissionData, { fields: SubmissionClientFields })
})